version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./functions/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd functions && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./functions/package.json" }}

      # run tests!
      - run: cd functions && npm test
      - store_test_results:
          path: junit.xml
      - run: 
          working_directory: ~/repo/functions/
          command: npm run build

      # deploy
      - run: 
          working_directory: ~/repo/
          command: ./functions/node_modules/.bin/firebase deploy --project $PROJECT_ID --token=$FIREBASE_TOKEN